set-option -g default-shell /usr/bin/fish

set-option -sa terminal-overrides ",xterm*:Tc"
set -g mouse on
set -g set-clipboard on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind x kill-pane
bind X kill-window

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D 
bind k select-pane -U
bind l select-pane -R
bind Escape copy-mode

bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

# status bar : 

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g window-status-current-style "fg=colour255,bg=default,bold"
set -g window-status-separator ""
set -g window-status-format "#[fg=colour240]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour240]#[default]"
set -g window-status-current-format "#[fg=colour252]#[default] #I:#W#{?window_flags,#{window_flags},} #[fg=colour252]#[default]"
set -g status-interval 5
set -g status-left "#S"
set -g status-right "" 

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set -g @sessionx-bind 'o'
#set -g @tmux-dotbar-position top
# set-option -g status off
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift Alt vim keys to switch windows
bind -r J previous-window
bind -r K next-window

# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
# set -g @catppuccin_flavour 'mocha'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'AngryMorrocoy/tmux-neolazygit'
# set -g @plugin 'vaaleyard/tmux-dotbar'

# persist
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# Auto-save tmux environment
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key R command-prompt -I "#S" "rename-session '%%'"
bind-key s run-shell "~/bin/ts"
bind t display-popup -E -w 80% -h 60% "ts"

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"


run -b '~/.config/tmux/tpm/tpm'
